name: Docker Image Build & CI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v0.2.x-alpha
    tags: [ tmp-rerun ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    name: build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create docker network
      run: docker network create data
    - name: Initialize environment variables
      run: ./init/load_fief_env.sh --user-email api-pgd@nonexisting.gov.br --user-password=123456*abcdef
    - name: Run all service containers
      run: docker --network data compose up -d --scale pgadmin=0 --wait --wait-timeout 90
    - name: curl
      run: docker run --rm --network data curlimages/curl:latest http://fief:8000
    - name: Configure Fief at runtime
      run: make fief-configure-instance
    - name: Run tests
      run: make tests
